version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env # Pass environment variables from .env file
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app:delegated
    depends_on:
      - mongodb
    networks:
      - condomate-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app:delegated
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
    depends_on:
      - backend
    networks:
      - condomate-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - condomate-network

volumes:
  mongodb_data:
    name: condomate-mongodb-data

networks:
  condomate-network:
    name: condomate-network
